CREATE TABLE IF not EXISTS NHAN_VIEN (
	HoDem 				VARCHAR(60) ,
  	Ten 				VARCHAR(60) ,
  	MSNV				INT PRIMARY KEY ,
  	NgaySinh 			DATE ,
  	DiaChi 				VARCHAR(60) ,
  	Luong 				INT DEFAULT 0,
  	MSTT 				INT REFERENCES NHAN_VIEN(MSNV),
  	MSP 				INT
);

CREATE TABLE if NOT EXISTS PHONG (
	TenPhong 			VARCHAR(60) UNIQUE,
  	MaPhong				INT PRIMARY KEY,
  	MaTP				INT
);

CREATE TABLE if NOT EXISTS DIA_DIEM_PHONG (
  	MaPhong 			INT  ,
  	DiaDiem 			VARCHAR(60) ,
  	PRIMARY KEY (MaPhong, DiaDiem)
	
);

CREATE TABLE if NOT EXISTS DU_AN (
	TenDA 				VARCHAR(60) ,
  	MaDA	 			INT PRIMARY KEY ,
  	DiaDiemDA 			VARCHAR(60) ,
  	MaPhongQL			INT 
	
);

CREATE TABLE if NOT EXISTS CHAM_CONG (
	MSNV			INT,
  	MSDA			INT,
  	GioCong			INT DEFAULT 0,
  	PRIMARY KEY (MSNV, MSDA)
);

CREATE TABLE if NOT EXISTS PHU_THUOC (
	MSNV			INT,
  	TenPT			VARCHAR(60) ,
  	NgaySinh		DATE ,
  	QuanHe			VARCHAR(60),
  	PRIMARY KEY (MSNV, TenPT)
);

ALTER TABLE NHAN_VIEN 
	DROP CONSTRAINT FK_A;

ALTER TABLE NHAN_VIEN 
	DROP CONSTRAINT FK_B;

ALTER TABLE PHONG 
	DROP CONSTRAINT FK_C;

ALTER TABLE DIA_DIEM_PHONG 
	DROP CONSTRAINT FK_D;

ALTER TABLE DU_AN 
	DROP CONSTRAINT FK_E;
	
ALTER TABLE CHAM_CONG 
	DROP CONSTRAINT FK_F;

ALTER TABLE CHAM_CONG 
	DROP CONSTRAINT FK_G;

ALTER TABLE PHU_THUOC 
	DROP CONSTRAINT FK_H;


SELECT * FROM NHAN_VIEN;